name: CI

on:
  pull_request: {}
  push: {}

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2

    - name: Initialize sandbox
      run: |
        SANDBOX_DIR=$(mktemp -d) || exit 1
        echo ::set-env name=SANDBOX_DIR::$SANDBOX_DIR
        ./makem.sh -vv --sandbox=$SANDBOX_DIR --install-deps --install-linters

    - name: Lint
      run: ./makem.sh -vv --sandbox=$SANDBOX_DIR lint

    - name: Test
      if: always()
      run: ./makem.sh -vv --sandbox=$SANDBOX_DIR test
